const commonFiles = [
  "apps/desktop/dist/**/*",
  "apps/desktop/assets/**/*",
  "dist-renderer/**/*",
  "packages/domain/dist/**/*",
  "packages/domain/package.json",
  "packages/pi-adapter/dist/**/*",
  "packages/pi-adapter/package.json",
  "packages/pi-host/dist/**/*",
  "packages/pi-host/package.json",
  "packages/permission-engine/dist/**/*",
  "packages/permission-engine/package.json",
  "packages/i18n/dist/**/*",
  "packages/i18n/package.json",
  "packages/ui-system/dist/**/*",
  "packages/ui-system/package.json",
  "package.json",
  "!.claude/**/*",
  "!.codex/**/*",
  "!.pi/**/*",
  "!.playwright-cli/**/*",
  "!.workbuddy/**/*",
  "!apps/desktop/src/**/*",
  "!apps/desktop/scripts/**/*",
  "!apps/desktop/native/**/*",
  "!apps/desktop/public/**/*",
  "!packages/*/src/**/*",
  "!docs/**/*",
  "!rules/**/*",
  "!AGENTS.md",
  "!CLAUDE.md",
  "!CONTRIBUTING.md",
  "!README*.md",
  "!SECURITY.md",
  "!**/*.map",
  "!**/*.d.ts",
  "!**/*.d.mts",
  "!**/*.d.cts",
  "!**/*.tsbuildinfo",
  "!node_modules/**/tree-sitter-bash/src/**",
  "!node_modules/**/tree-sitter-bash/grammar.js",
];

module.exports = {
  appId: "com.pideck.desktop",
  productName: "PiDeck",
  directories: { output: "release" },
  asar: true,
  asarUnpack: ["**/*.node", "apps/desktop/assets/**/*"],
  npmRebuild: false,
  files: commonFiles,
  win: {
    target: { target: "nsis", arch: ["x64"] },
    icon: "apps/desktop/assets/pideck-icon.ico",
    files: [
      ...commonFiles,
      "!node_modules/**/@mariozechner/clipboard-{darwin,linux}*/**",
      "!node_modules/**/@mariozechner/clipboard-win32-arm64-msvc/**",
      "!node_modules/**/prebuilds/{darwin,linux}-*/**",
      "!node_modules/**/prebuilds/win32-arm64/**",
      "!node_modules/**/native/{darwin,linux}/**",
      "!node_modules/**/native/win32/prebuilds/win32-arm64/**",
    ],
  },
  nsis: {
    oneClick: false,
    perMachine: false,
    allowToChangeInstallationDirectory: true,
  },
  mac: {
    target: ["dmg"],
    icon: "apps/desktop/assets/pideck-icon.icns",
    category: "public.app-category.developer-tools",
    files: [
      ...commonFiles,
      "!node_modules/**/@mariozechner/clipboard-{win32,linux}*/**",
      "!node_modules/**/prebuilds/{win32,linux}-*/**",
      "!node_modules/**/native/{win32,linux}/**",
    ],
  },
  dmg: { title: "PiDeck" },
};
