export type Theme = "light" | "dark";
export type SuggestionMode = "slash" | "mention" | null;
export type WorkingPhase = "thinking" | "responding" | "tool" | "compacting" | null;
export type MessageLoad = { status: "idle" | "loading" | "ready" | "error"; error?: string };
export type ActivityStep = {
  id: string;
  kind: "thinking" | "tool";
  label: string;
  detail?: string;
  args?: unknown;
  result?: unknown;
  startedAt: number;
  endedAt?: number;
  durationMs?: number;
  timing?: "measured" | "unknown";
  isError?: boolean;
};
export type TaskUiState = {
  isSending: boolean;
  isCompacting: boolean;
  streamText: string;
  workingPhase: WorkingPhase;
  activity: ActivityStep[];
  completedActivity: ActivityStep[][];
  toolName?: string;
  approval?: { requestId: string; toolName: string; args?: unknown };
};
export type AuthPromptOption = { id: string; label: string; description?: string };
export type AuthPromptState = {
  requestId: string;
  type: "text" | "secret" | "select" | "manual_code";
  message: string;
  placeholder: string;
  value: string;
  options?: AuthPromptOption[];
};
export type ImageAttachment = { id: string; data: string; mimeType: string; name: string };
export type SentImageMessage = { text: string; images: ImageAttachment[] };
export type PreviewImage = { src: string; alt: string };
export type ImageContextMenuState = { x: number; y: number; image: PreviewImage };
export type ProviderFilter = "all" | "configured" | "expired" | "missing";
